name: dbt Debug
on:
  push:
    branches:
     - testing
     - main
  workflow_dispatch:
jobs:
  run-dbt: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Google credentials
        env:
          KEYFILE: ${{ secrets.KEYFILE }}
        run: |
          echo "${{ secrets.KEYFILE }}" 
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi --no-root
      - name: Debug swm_dev
        run: poetry run dbt debug -t swm_dev
      - name: Debug swm_prod
        run: poetry run dbt debug -t swm_prod
      - name: Debug acme_dev
        run: poetry run dbt debug -t acme_dev
      - name: Debug acme_prod
        run: poetry run dbt debug -t acme_prod
